geoffreyadebonojo/quantified-self-be

db/migrations/20190129174512_create-days.js
db/migrations/20190129175344_create-meals.js
db/migrations/20190129175643_create-meal_foods.js
knexfile.js

____  Bug Fix
____  Refactor
Created database and migrations, then ran migrations.
closes #1 

Create and migrate database

---

server.js

____  Bug Fix
____  Refactor
Creates endpoint for GET foods.
closes #2 

Create endpoint for GET foods

---

server.js

____  Bug Fix
____  Refactor
Creates endpoint for GET foods/:id. 
closes #3 

Create endpoint for GET foods/:id

---

server.js

____  Bug Fix
____  Refactor
Creates endpoint for POST foods
closes #4 

Create endpoint for POST foods

---

index.js

____  Bug Fix
____  Refactor
Configures endpoint to DELETE food.
closes #6 

Implemented endpoint to delete food

---

index.js
server.js

____  Bug Fix
____  Refactor
Configures endpoint to update (PATCH) a food
closes #5 

5 configure endpoint patch food

---

index.js

__x__  Bug Fix
____  Refactor
DELETE route got lost somehow in merging. reinserted this block and re-pushed. 
closes #6 

Configure endpoint to delete a food

---

index.js
package-lock.json
package.json
test/routes.spec.js

____  Bug Fix
____  Refactor
closes #

16 write tests for existing api endpoints

---

.travis.yml
db/seeds/dev/01_foods.js
package-lock.json
package.json
test/routes.spec.js

____  Bug Fix
____  Refactor
closes #19 Configures Travis CI

Configure Travis CI

---

db/seeds/dev/02_days.js
index.js
test/routes.spec.js

____  Bug Fix
____  Refactor
closes #24 Configure endpoint for /days and build test 

Create GET /days and test

---

db/seeds/dev/04_meal_foods.js
index.js
test/routes.spec.js

____  Bug Fix
____  Refactor
closes #8 
Also added dependent destroy to meal_foods in the endpoint to delete foods

Configure endpoint for GET meal/:meal_id/foods

---

index.js
test/routes.spec.js

____  Bug Fix
____  Refactor
closes #9 create POST endpoint for adding a food to a meal

9 configure endpoint to post food to meal

---

index.js
test/routes.spec.js

____  Bug Fix
____  Refactor
Configures endpoint to remove a food from a meal using TDD.
closes #10 

Configure endpoint to remove a food from a meal

---

knexfile.js
package-lock.json
package.json

____  Bug Fix
____  Refactor
closes #30 Add configuration for heroku

Heroku deployment

---

db/seeds/dev/04_meal_foods.js
index.js
test/routes.spec.js

__x__  Bug Fix
__x__  Refactor
Refactors tests, adds sad path tests, fixes any bugs exposed by newly improved test suite.
closes #33 

33 refactor tests

---

index.js

____  Bug Fix
____  Refactor
Adds code for CORS functionality. @geoffreyadebonojo shall we push this to master and try it? 
closes #36 

Add CORS functionality

---

test/routes.spec.js

____  Bug Fix
__x__  Refactor
Adds test expectations to verify that food ID's are being sent back in response body
closes #

Add test expectations for foods index response properties

---

index.js

__x__  Bug Fix
____  Refactor
Orders /foods response by food ID
@geoffreyadebonojo please review. thanks!
closes #39 

Order foods by ID at /foods endpoint

---

index.js
test/routes.spec.js

__x__  Bug Fix
____  Refactor
Implements changes/fix for GET /meals endpoint. New functionality sends API response with food objects included, where relevant meal_foods exist, within the "foods" property of each meal. 
@geoffreyadebonojo please review. Thanks!
closes #41 
- [] There is no unused/commented out code

Fix GET meals endpoint to show meal foods

---

index.js
lib/controllers/foods_controller.js
lib/models/food.js
lib/routes/api/v1/foods.js
test/routes.spec.js

____  Bug Fix
____  Refactor
Issue with creating meals for newly created day WIP

44 build out days api endpoints

---

index.js
test/routes.spec.js

__x__  Bug Fix
____  Refactor
Implements POST endpoint to add new meals for a given day.
@geoffreyadebonojo please review. nice work and thanks! 
closes #44 closes #46 
- [] There is no unused/commented out code

Implement POST days/:day_id/meals endpoint through TDD

---

index.js
test/routes.spec.js

____  Bug Fix
__x__  Refactor
Refactors meals endpoint to return date for each meal
closes #

Refactor meals endpoint to return dates for meals
